### ISSUE TITLE
Error message is output after running the metric agent installer

### ISSUE THREAD

**Issue by haruki-yamanashi** [monasca/monasca-agents-installer#10]
After running the metric agent installer, following message was output.
```
Failed to execute operation: Invalid argument
```
When I see this message at first, I misunderstand that installation is failed.

In my understanding, this message means "installation was succeeded but some of plugin are not detected automatically".
So I think it's better to change this message like above.

**Comment by haruki-yamanashi** [comment]
@samirjorina @digitalfishpond @witekest

**Comment by digitalfishpond** [comment]
Could you provide the full command you used that generated this message, and the output? This is not a message from the installer, so I'd need to find out where it's come from before determining if it's something we can/should change.

**Comment by haruki-yamanashi** [comment]
@digitalfishpond 
Sorry, I misunderstood.
As far as I checked, `Failed to execute operation: Invalid argument` is output when running `systemctl enable monasca-agent`.
